name: xmPlugin
version: '${project.version}'
main: me.carbonnetwork.xmplugin.XmPlugin
api-version: '1.16'

commands:
  kit:
    description: Kit command yeyeah!!
    usage: /<command>
  feedme:
    description: Feeling hungry?
    usage: /<command>
  setchatcolor:
    description: Set player chat color
    usage: /<command>>
  spawnnpc:
    description: Spawn an NPC
    usage: /<command>
  removenpc:
    description: Remove an NPC
    usage: /<command>