name: xmPlugin
version: '${project.version}'
main: me.carbonnetwork.xmplugin.XmPlugin
api-version: '1.20'

commands:
  kit:
    description: Kit command yeyeah!!
    usage: /<command>
  feedme:
    description: Feeling hungry?
    usage: /<command>
  setchatcolor:
    description: Set player chat color
    usage: /setchatcolor <color>